export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    cookTime: '20-30',
    price: 20,
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    cookTime: '10-15',
    price: 8,
    favorite: false,
    origins: ['usa'],
    stars: 4,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id: '4',
    name: 'Fried Chicken',
    cookTime: '15-25',
    price: 12,
    favorite: true,
    origins: ['usa'],
    stars: 4.8,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Chicken', 'Dinner'],
  },
  {
    id: '5',
    name: 'Vegetable Pizza',
    cookTime: '10-20',
    price: 11,
    favorite: false,
    origins: ['italy'],
    stars: 4.2,
    imageUrl: 'food-5.jpg',
    tags: ['Pizza', 'Vegetarian', 'Lunch'],
  },
  {
    id: '6',
    name: 'Pasta',
    cookTime: '15-20',
    price: 14,
    favorite: true,
    origins: ['italy'],
    stars: 4.9,
    imageUrl: 'food-6.jpg',
    tags: ['Pasta', 'Dinner', 'Italian'],
  },
];


export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 3 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 4 },
  { name: 'SlowFood', count: 1 },
  { name: 'Burger', count: 1 },
  { name: 'Chicken', count: 1 },
  { name: 'Dinner', count: 2 },
  { name: 'Vegetarian', count: 1 },
  { name: 'Pasta', count: 1 },
  { name: 'Italian', count: 1 },
];